apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" . }}-config
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
data:
  JAVA_OPTS: {{ .Values.app.javaOpts | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.app.profile | quote }}
  TZ: {{ .Values.app.timezone | quote }}
  SERVER_PORT: {{ .Values.service.port | quote }}
  {{- if .Values.vault.enabled }}
  VAULT_ENABLED: "true"
  VAULT_ROLE: {{ .Values.vault.role | quote }}
  {{- end }}

